---
cluster_name: "9wnp4"
base_domain: "dynamic2.redhatworkshops.io"
subnet_cidr: "192.168.69.0/24"
vsphere_network: "segment-sandbox-9wnp4"
api_vip: "192.168.69.201"
ingress_vip: "192.168.69.202"
vcenter_folder: "/SDDC-Datacenter/vm/Workloads/sandbox-9wnp4"
vcenter_username: "sandbox-9wnp4@demo"
vcenter_password: "{{ vault_site_a_vcenter_password }}"
#ansible_password: "{{ vault_site_a_bastion_password }}"
ansible_ssh_private_key_file: "~/.ssh/id_rsa"
ansible_become_password: "{{ vault_site_a_bastion_password }}"

vcenter_compute_cluster: "/SDDC-Datacenter/host/Cluster-1"
vcenter_datastore: "/SDDC-Datacenter/datastore/workload_share_FZZZD"
vcenter_resource_pool: ""
intersite_remote_underlay_cidr: "192.168.70.0/24"
intersite_remote_gateway: "192.168.69.1"
intersite_remote_bastion_ip: "192.168.70.10"
