---
cluster_name: "site-b"
base_domain: "rhdz5.dynamic2.redhatworkshops.io"
subnet_cidr: "192.168.70.0/24"
vsphere_network: "segment-sandbox-rhdz5"
api_vip: "192.168.70.201"
ingress_vip: "192.168.70.202"
vcenter_folder: "/SDDC-Datacenter/vm/Workloads/sandbox-rhdz5"
vcenter_username: "sandbox-rhdz5@demo"
vcenter_password: "{{ vault_site_b_vcenter_password }}"
ansible_password: "{{ vault_site_b_bastion_password }}"
ansible_become_password: "{{ vault_site_b_bastion_password }}"
