---
all:
  vars:
    ansible_user: lab-user
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    site_a:
      hosts:
        site-a-bastion:
          ansible_host: bastion-9wnp4.9wnp4.dynamic2.redhatworkshops.io
          site_id: site_a
    site_b:
      hosts:
        site-b-bastion:
          ansible_host: bastion-rhdz5.rhdz5.dynamic2.redhatworkshops.io
          site_id: site_b
